import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { minify } from 'html-minifier-terser';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const landingPath = path.join(__dirname, '../landing/index.html');
const isProduction = process.env.NODE_ENV === 'production' || process.env.MINIFY === 'true';

const minifyOptions = {
    caseSensitive: false,
    collapseBooleanAttributes: true,
    collapseInlineTagWhitespace: false,
    collapseWhitespace: true,
    conservativeCollapse: false,
    continueOnParseError: true,
    decodeEntities: true,
    html5: true,
    ignoreCustomComments: [],
    ignoreCustomFragments: [/<\?[\s\S]*?\?>/],
    includeAutoGeneratedTags: false,
    keepClosingSlash: false,
    maxLineLength: 0,
    minifyCSS: true,
    minifyJS: true,
    minifyURLs: false,
    noNewlinesBeforeTagClose: false,
    preserveLineBreaks: false,
    preventAttributesEscaping: false,
    processConditionalComments: true,
    processScripts: ['text/html'],
    quoteCharacter: '"',
    removeAttributeQuotes: true,
    removeComments: true,
    removeEmptyAttributes: true,
    removeEmptyElements: false,
    removeOptionalTags: false,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    removeTagWhitespace: true,
    sortAttributes: false,
    sortClassName: false,
    trimCustomFragments: true,
    useShortDoctype: true,
};

if (isProduction) {
    console.log('🔨 Minificando HTML para producción con html-minifier-terser...');
    const html = fs.readFileSync(landingPath, 'utf8');
    const originalSize = html.length;
    
    try {
        const minified = await minify(html, minifyOptions);
        const minifiedSize = minified.length;
        
        fs.writeFileSync(landingPath, minified);
        
        console.log(`✅ HTML minificado:`);
        console.log(`   Original: ${(originalSize / 1024).toFixed(2)} KB (${originalSize.toLocaleString()} bytes)`);
        console.log(`   Minificado: ${(minifiedSize / 1024).toFixed(2)} KB (${minifiedSize.toLocaleString()} bytes)`);
        console.log(`   Reducción: ${((1 - minifiedSize / originalSize) * 100).toFixed(1)}%`);
    } catch (error) {
        console.error('❌ Error al minificar HTML:', error.message);
        process.exit(1);
    }
} else {
    console.log('ℹ️  Modo desarrollo: HTML no se minifica');
    console.log('   Para minificar, ejecuta con: MINIFY=true node scripts/minify-html.js');
}
